apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
- path: config/release
  contents:
  - path: .
    http:
      url: https://storage.googleapis.com/beam-releases/kpack-release-yaml/release-0.5.3-rc.5.yaml
- path: test
  contents:
  - path: .
    git:
      url: https://github.com/pivotal/kpack
      ref: 2c3432315ecfa15e3ee71b58b030593f533e11c4
    newRootPath: test
