apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
- path: config/release
  contents:
  - path: .
    http:
      url: https://storage.googleapis.com/beam-releases/kpack-release-yaml/release-0.6.2-rc.1.yaml
- path: test
  contents:
  - path: .
    git:
      url: https://github.com/pivotal/kpack
      ref: a70f00b2ec39a024243bb4cec4b6596371f7357d
    newRootPath: test
