apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
- path: config/release
  contents:
  - path: .
    http:
      url: https://storage.googleapis.com/beam-releases/kpack-release-yaml/release-0.6.1-rc.11.yaml
- path: test
  contents:
  - path: .
    git:
      url: https://github.com/pivotal/kpack
      ref: 1d5282d726547ec32acfb153574353cc424b5a52
    newRootPath: test
