---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kpack-control-plane
value: 10000
globalDefault: false
description: "Super High priority class for kpack control plane components"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kpack-build-high-priority
value: 1000
globalDefault: false
description: "High priority class for kpack builds triggered by user changes."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kpack-build-low-priority
value: 1
globalDefault: false
preemptionPolicy: Never
description: "Low priority class for kpack builds triggered by operator changes."
